/**
 * generated by Xtext 2.17.0
 */
package br.ufes.inf;

import br.ufes.inf.StoryGenStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class StoryGenStandaloneSetup extends StoryGenStandaloneSetupGenerated {
  public static void doSetup() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method createInjectorAndDoEMFRegistration() is undefined for the type StoryGenStandaloneSetup");
  }
}
