/**
 * generated by Xtext 2.17.0
 */
package br.ufes.inf;

import br.ufes.inf.AbstractStoryGenRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class StoryGenRuntimeModule extends AbstractStoryGenRuntimeModule {
}
