/**
 * generated by Xtext 2.14.0
 */
package br.ufes.inf.mdd.trab2.storyGenerator;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.inf.mdd.trab2.storyGenerator.Condition#getBoolExp <em>Bool Exp</em>}</li>
 * </ul>
 *
 * @see br.ufes.inf.mdd.trab2.storyGenerator.StoryGeneratorPackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends EObject
{
  /**
   * Returns the value of the '<em><b>Bool Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bool Exp</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bool Exp</em>' containment reference.
   * @see #setBoolExp(BoolExp)
   * @see br.ufes.inf.mdd.trab2.storyGenerator.StoryGeneratorPackage#getCondition_BoolExp()
   * @model containment="true"
   * @generated
   */
  BoolExp getBoolExp();

  /**
   * Sets the value of the '{@link br.ufes.inf.mdd.trab2.storyGenerator.Condition#getBoolExp <em>Bool Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bool Exp</em>' containment reference.
   * @see #getBoolExp()
   * @generated
   */
  void setBoolExp(BoolExp value);

} // Condition
