/**
 * generated by Xtext 2.14.0
 */
package br.ufes.inf.mdd.trab2.storyGenerator;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see br.ufes.inf.mdd.trab2.storyGenerator.StoryGeneratorFactory
 * @model kind="package"
 * @generated
 */
public interface StoryGeneratorPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "storyGenerator";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ufes.br/inf/mdd/trab2/StoryGenerator";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "storyGenerator";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  StoryGeneratorPackage eINSTANCE = br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl.init();

  /**
   * The meta object id for the '{@link br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryImpl <em>Story</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryImpl
   * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl#getStory()
   * @generated
   */
  int STORY = 0;

  /**
   * The feature id for the '<em><b>World</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORY__WORLD = 0;

  /**
   * The feature id for the '<em><b>Events</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORY__EVENTS = 1;

  /**
   * The number of structural features of the '<em>Story</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.ufes.inf.mdd.trab2.storyGenerator.impl.WorldImpl <em>World</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.WorldImpl
   * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl#getWorld()
   * @generated
   */
  int WORLD = 1;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORLD__ATTRIBUTES = 0;

  /**
   * The number of structural features of the '<em>World</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORLD_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link br.ufes.inf.mdd.trab2.storyGenerator.impl.AttributeImpl <em>Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.AttributeImpl
   * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl#getAttribute()
   * @generated
   */
  int ATTRIBUTE = 2;

  /**
   * The feature id for the '<em><b>Attr Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__ATTR_TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__NAME = 1;

  /**
   * The number of structural features of the '<em>Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.ufes.inf.mdd.trab2.storyGenerator.impl.EventImpl <em>Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.EventImpl
   * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl#getEvent()
   * @generated
   */
  int EVENT = 3;

  /**
   * The feature id for the '<em><b>Abstract</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__ABSTRACT = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__NAME = 1;

  /**
   * The feature id for the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__SUPER_TYPE = 2;

  /**
   * The feature id for the '<em><b>Conditions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__CONDITIONS = 3;

  /**
   * The number of structural features of the '<em>Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link br.ufes.inf.mdd.trab2.storyGenerator.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.ConditionImpl
   * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 4;

  /**
   * The feature id for the '<em><b>Bool Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__BOOL_EXP = 0;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link br.ufes.inf.mdd.trab2.storyGenerator.impl.BoolExpImpl <em>Bool Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.BoolExpImpl
   * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl#getBoolExp()
   * @generated
   */
  int BOOL_EXP = 5;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_EXP__LEFT = 0;

  /**
   * The feature id for the '<em><b>Bool Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_EXP__BOOL_OP = 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_EXP__RIGHT = 2;

  /**
   * The feature id for the '<em><b>Par Bool Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_EXP__PAR_BOOL_EXP = 3;

  /**
   * The feature id for the '<em><b>Binary Bool</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_EXP__BINARY_BOOL = 4;

  /**
   * The feature id for the '<em><b>Binary Qnty</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_EXP__BINARY_QNTY = 5;

  /**
   * The feature id for the '<em><b>Negate Bool Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_EXP__NEGATE_BOOL_EXP = 6;

  /**
   * The feature id for the '<em><b>Unary Bool</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_EXP__UNARY_BOOL = 7;

  /**
   * The number of structural features of the '<em>Bool Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_EXP_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link br.ufes.inf.mdd.trab2.storyGenerator.impl.BinaryBoolExpImpl <em>Binary Bool Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.BinaryBoolExpImpl
   * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl#getBinaryBoolExp()
   * @generated
   */
  int BINARY_BOOL_EXP = 6;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINARY_BOOL_EXP__LEFT = 0;

  /**
   * The feature id for the '<em><b>Bool Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINARY_BOOL_EXP__BOOL_OP = 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINARY_BOOL_EXP__RIGHT = 2;

  /**
   * The number of structural features of the '<em>Binary Bool Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINARY_BOOL_EXP_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link br.ufes.inf.mdd.trab2.storyGenerator.impl.BinaryQntyExpImpl <em>Binary Qnty Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.BinaryQntyExpImpl
   * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl#getBinaryQntyExp()
   * @generated
   */
  int BINARY_QNTY_EXP = 7;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINARY_QNTY_EXP__LEFT = 0;

  /**
   * The feature id for the '<em><b>Num Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINARY_QNTY_EXP__NUM_OP = 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINARY_QNTY_EXP__RIGHT = 2;

  /**
   * The number of structural features of the '<em>Binary Qnty Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINARY_QNTY_EXP_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link br.ufes.inf.mdd.trab2.storyGenerator.impl.UnaryBoolExpImpl <em>Unary Bool Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.UnaryBoolExpImpl
   * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl#getUnaryBoolExp()
   * @generated
   */
  int UNARY_BOOL_EXP = 8;

  /**
   * The feature id for the '<em><b>Id</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_BOOL_EXP__ID = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_BOOL_EXP__VALUE = 1;

  /**
   * The number of structural features of the '<em>Unary Bool Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_BOOL_EXP_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.ufes.inf.mdd.trab2.storyGenerator.impl.NegateBoolExpImpl <em>Negate Bool Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.NegateBoolExpImpl
   * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl#getNegateBoolExp()
   * @generated
   */
  int NEGATE_BOOL_EXP = 9;

  /**
   * The feature id for the '<em><b>Bool Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEGATE_BOOL_EXP__BOOL_EXP = 0;

  /**
   * The number of structural features of the '<em>Negate Bool Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEGATE_BOOL_EXP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link br.ufes.inf.mdd.trab2.storyGenerator.impl.UnaryQuantityExpImpl <em>Unary Quantity Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.UnaryQuantityExpImpl
   * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl#getUnaryQuantityExp()
   * @generated
   */
  int UNARY_QUANTITY_EXP = 10;

  /**
   * The feature id for the '<em><b>Id</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_QUANTITY_EXP__ID = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_QUANTITY_EXP__VALUE = 1;

  /**
   * The number of structural features of the '<em>Unary Quantity Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_QUANTITY_EXP_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.ufes.inf.mdd.trab2.storyGenerator.AttrType <em>Attr Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.inf.mdd.trab2.storyGenerator.AttrType
   * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl#getAttrType()
   * @generated
   */
  int ATTR_TYPE = 11;

  /**
   * The meta object id for the '{@link br.ufes.inf.mdd.trab2.storyGenerator.BooleanValue <em>Boolean Value</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.inf.mdd.trab2.storyGenerator.BooleanValue
   * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl#getBooleanValue()
   * @generated
   */
  int BOOLEAN_VALUE = 12;

  /**
   * The meta object id for the '{@link br.ufes.inf.mdd.trab2.storyGenerator.NumOp <em>Num Op</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.inf.mdd.trab2.storyGenerator.NumOp
   * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl#getNumOp()
   * @generated
   */
  int NUM_OP = 13;

  /**
   * The meta object id for the '{@link br.ufes.inf.mdd.trab2.storyGenerator.BoolOp <em>Bool Op</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.inf.mdd.trab2.storyGenerator.BoolOp
   * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl#getBoolOp()
   * @generated
   */
  int BOOL_OP = 14;


  /**
   * Returns the meta object for class '{@link br.ufes.inf.mdd.trab2.storyGenerator.Story <em>Story</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Story</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.Story
   * @generated
   */
  EClass getStory();

  /**
   * Returns the meta object for the containment reference '{@link br.ufes.inf.mdd.trab2.storyGenerator.Story#getWorld <em>World</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>World</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.Story#getWorld()
   * @see #getStory()
   * @generated
   */
  EReference getStory_World();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufes.inf.mdd.trab2.storyGenerator.Story#getEvents <em>Events</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Events</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.Story#getEvents()
   * @see #getStory()
   * @generated
   */
  EReference getStory_Events();

  /**
   * Returns the meta object for class '{@link br.ufes.inf.mdd.trab2.storyGenerator.World <em>World</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>World</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.World
   * @generated
   */
  EClass getWorld();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufes.inf.mdd.trab2.storyGenerator.World#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.World#getAttributes()
   * @see #getWorld()
   * @generated
   */
  EReference getWorld_Attributes();

  /**
   * Returns the meta object for class '{@link br.ufes.inf.mdd.trab2.storyGenerator.Attribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.Attribute
   * @generated
   */
  EClass getAttribute();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.inf.mdd.trab2.storyGenerator.Attribute#getAttrType <em>Attr Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Attr Type</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.Attribute#getAttrType()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_AttrType();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.inf.mdd.trab2.storyGenerator.Attribute#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.Attribute#getName()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Name();

  /**
   * Returns the meta object for class '{@link br.ufes.inf.mdd.trab2.storyGenerator.Event <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.Event
   * @generated
   */
  EClass getEvent();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.inf.mdd.trab2.storyGenerator.Event#isAbstract <em>Abstract</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Abstract</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.Event#isAbstract()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Abstract();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.inf.mdd.trab2.storyGenerator.Event#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.Event#getName()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Name();

  /**
   * Returns the meta object for the reference '{@link br.ufes.inf.mdd.trab2.storyGenerator.Event#getSuperType <em>Super Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Super Type</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.Event#getSuperType()
   * @see #getEvent()
   * @generated
   */
  EReference getEvent_SuperType();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufes.inf.mdd.trab2.storyGenerator.Event#getConditions <em>Conditions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Conditions</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.Event#getConditions()
   * @see #getEvent()
   * @generated
   */
  EReference getEvent_Conditions();

  /**
   * Returns the meta object for class '{@link br.ufes.inf.mdd.trab2.storyGenerator.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for the containment reference '{@link br.ufes.inf.mdd.trab2.storyGenerator.Condition#getBoolExp <em>Bool Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Bool Exp</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.Condition#getBoolExp()
   * @see #getCondition()
   * @generated
   */
  EReference getCondition_BoolExp();

  /**
   * Returns the meta object for class '{@link br.ufes.inf.mdd.trab2.storyGenerator.BoolExp <em>Bool Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bool Exp</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.BoolExp
   * @generated
   */
  EClass getBoolExp();

  /**
   * Returns the meta object for the containment reference '{@link br.ufes.inf.mdd.trab2.storyGenerator.BoolExp#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.BoolExp#getLeft()
   * @see #getBoolExp()
   * @generated
   */
  EReference getBoolExp_Left();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.inf.mdd.trab2.storyGenerator.BoolExp#getBoolOp <em>Bool Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bool Op</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.BoolExp#getBoolOp()
   * @see #getBoolExp()
   * @generated
   */
  EAttribute getBoolExp_BoolOp();

  /**
   * Returns the meta object for the containment reference '{@link br.ufes.inf.mdd.trab2.storyGenerator.BoolExp#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.BoolExp#getRight()
   * @see #getBoolExp()
   * @generated
   */
  EReference getBoolExp_Right();

  /**
   * Returns the meta object for the containment reference '{@link br.ufes.inf.mdd.trab2.storyGenerator.BoolExp#getParBoolExp <em>Par Bool Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Par Bool Exp</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.BoolExp#getParBoolExp()
   * @see #getBoolExp()
   * @generated
   */
  EReference getBoolExp_ParBoolExp();

  /**
   * Returns the meta object for the containment reference '{@link br.ufes.inf.mdd.trab2.storyGenerator.BoolExp#getBinaryBool <em>Binary Bool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Binary Bool</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.BoolExp#getBinaryBool()
   * @see #getBoolExp()
   * @generated
   */
  EReference getBoolExp_BinaryBool();

  /**
   * Returns the meta object for the containment reference '{@link br.ufes.inf.mdd.trab2.storyGenerator.BoolExp#getBinaryQnty <em>Binary Qnty</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Binary Qnty</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.BoolExp#getBinaryQnty()
   * @see #getBoolExp()
   * @generated
   */
  EReference getBoolExp_BinaryQnty();

  /**
   * Returns the meta object for the containment reference '{@link br.ufes.inf.mdd.trab2.storyGenerator.BoolExp#getNegateBoolExp <em>Negate Bool Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Negate Bool Exp</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.BoolExp#getNegateBoolExp()
   * @see #getBoolExp()
   * @generated
   */
  EReference getBoolExp_NegateBoolExp();

  /**
   * Returns the meta object for the containment reference '{@link br.ufes.inf.mdd.trab2.storyGenerator.BoolExp#getUnaryBool <em>Unary Bool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Unary Bool</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.BoolExp#getUnaryBool()
   * @see #getBoolExp()
   * @generated
   */
  EReference getBoolExp_UnaryBool();

  /**
   * Returns the meta object for class '{@link br.ufes.inf.mdd.trab2.storyGenerator.BinaryBoolExp <em>Binary Bool Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Binary Bool Exp</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.BinaryBoolExp
   * @generated
   */
  EClass getBinaryBoolExp();

  /**
   * Returns the meta object for the containment reference '{@link br.ufes.inf.mdd.trab2.storyGenerator.BinaryBoolExp#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.BinaryBoolExp#getLeft()
   * @see #getBinaryBoolExp()
   * @generated
   */
  EReference getBinaryBoolExp_Left();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.inf.mdd.trab2.storyGenerator.BinaryBoolExp#getBoolOp <em>Bool Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bool Op</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.BinaryBoolExp#getBoolOp()
   * @see #getBinaryBoolExp()
   * @generated
   */
  EAttribute getBinaryBoolExp_BoolOp();

  /**
   * Returns the meta object for the containment reference '{@link br.ufes.inf.mdd.trab2.storyGenerator.BinaryBoolExp#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.BinaryBoolExp#getRight()
   * @see #getBinaryBoolExp()
   * @generated
   */
  EReference getBinaryBoolExp_Right();

  /**
   * Returns the meta object for class '{@link br.ufes.inf.mdd.trab2.storyGenerator.BinaryQntyExp <em>Binary Qnty Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Binary Qnty Exp</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.BinaryQntyExp
   * @generated
   */
  EClass getBinaryQntyExp();

  /**
   * Returns the meta object for the containment reference '{@link br.ufes.inf.mdd.trab2.storyGenerator.BinaryQntyExp#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.BinaryQntyExp#getLeft()
   * @see #getBinaryQntyExp()
   * @generated
   */
  EReference getBinaryQntyExp_Left();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.inf.mdd.trab2.storyGenerator.BinaryQntyExp#getNumOp <em>Num Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Num Op</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.BinaryQntyExp#getNumOp()
   * @see #getBinaryQntyExp()
   * @generated
   */
  EAttribute getBinaryQntyExp_NumOp();

  /**
   * Returns the meta object for the containment reference '{@link br.ufes.inf.mdd.trab2.storyGenerator.BinaryQntyExp#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.BinaryQntyExp#getRight()
   * @see #getBinaryQntyExp()
   * @generated
   */
  EReference getBinaryQntyExp_Right();

  /**
   * Returns the meta object for class '{@link br.ufes.inf.mdd.trab2.storyGenerator.UnaryBoolExp <em>Unary Bool Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Unary Bool Exp</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.UnaryBoolExp
   * @generated
   */
  EClass getUnaryBoolExp();

  /**
   * Returns the meta object for the reference '{@link br.ufes.inf.mdd.trab2.storyGenerator.UnaryBoolExp#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Id</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.UnaryBoolExp#getId()
   * @see #getUnaryBoolExp()
   * @generated
   */
  EReference getUnaryBoolExp_Id();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.inf.mdd.trab2.storyGenerator.UnaryBoolExp#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.UnaryBoolExp#getValue()
   * @see #getUnaryBoolExp()
   * @generated
   */
  EAttribute getUnaryBoolExp_Value();

  /**
   * Returns the meta object for class '{@link br.ufes.inf.mdd.trab2.storyGenerator.NegateBoolExp <em>Negate Bool Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Negate Bool Exp</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.NegateBoolExp
   * @generated
   */
  EClass getNegateBoolExp();

  /**
   * Returns the meta object for the containment reference '{@link br.ufes.inf.mdd.trab2.storyGenerator.NegateBoolExp#getBoolExp <em>Bool Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Bool Exp</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.NegateBoolExp#getBoolExp()
   * @see #getNegateBoolExp()
   * @generated
   */
  EReference getNegateBoolExp_BoolExp();

  /**
   * Returns the meta object for class '{@link br.ufes.inf.mdd.trab2.storyGenerator.UnaryQuantityExp <em>Unary Quantity Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Unary Quantity Exp</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.UnaryQuantityExp
   * @generated
   */
  EClass getUnaryQuantityExp();

  /**
   * Returns the meta object for the reference '{@link br.ufes.inf.mdd.trab2.storyGenerator.UnaryQuantityExp#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Id</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.UnaryQuantityExp#getId()
   * @see #getUnaryQuantityExp()
   * @generated
   */
  EReference getUnaryQuantityExp_Id();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.inf.mdd.trab2.storyGenerator.UnaryQuantityExp#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.UnaryQuantityExp#getValue()
   * @see #getUnaryQuantityExp()
   * @generated
   */
  EAttribute getUnaryQuantityExp_Value();

  /**
   * Returns the meta object for enum '{@link br.ufes.inf.mdd.trab2.storyGenerator.AttrType <em>Attr Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Attr Type</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.AttrType
   * @generated
   */
  EEnum getAttrType();

  /**
   * Returns the meta object for enum '{@link br.ufes.inf.mdd.trab2.storyGenerator.BooleanValue <em>Boolean Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Boolean Value</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.BooleanValue
   * @generated
   */
  EEnum getBooleanValue();

  /**
   * Returns the meta object for enum '{@link br.ufes.inf.mdd.trab2.storyGenerator.NumOp <em>Num Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Num Op</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.NumOp
   * @generated
   */
  EEnum getNumOp();

  /**
   * Returns the meta object for enum '{@link br.ufes.inf.mdd.trab2.storyGenerator.BoolOp <em>Bool Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Bool Op</em>'.
   * @see br.ufes.inf.mdd.trab2.storyGenerator.BoolOp
   * @generated
   */
  EEnum getBoolOp();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  StoryGeneratorFactory getStoryGeneratorFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryImpl <em>Story</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryImpl
     * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl#getStory()
     * @generated
     */
    EClass STORY = eINSTANCE.getStory();

    /**
     * The meta object literal for the '<em><b>World</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STORY__WORLD = eINSTANCE.getStory_World();

    /**
     * The meta object literal for the '<em><b>Events</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STORY__EVENTS = eINSTANCE.getStory_Events();

    /**
     * The meta object literal for the '{@link br.ufes.inf.mdd.trab2.storyGenerator.impl.WorldImpl <em>World</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.WorldImpl
     * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl#getWorld()
     * @generated
     */
    EClass WORLD = eINSTANCE.getWorld();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WORLD__ATTRIBUTES = eINSTANCE.getWorld_Attributes();

    /**
     * The meta object literal for the '{@link br.ufes.inf.mdd.trab2.storyGenerator.impl.AttributeImpl <em>Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.AttributeImpl
     * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl#getAttribute()
     * @generated
     */
    EClass ATTRIBUTE = eINSTANCE.getAttribute();

    /**
     * The meta object literal for the '<em><b>Attr Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__ATTR_TYPE = eINSTANCE.getAttribute_AttrType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__NAME = eINSTANCE.getAttribute_Name();

    /**
     * The meta object literal for the '{@link br.ufes.inf.mdd.trab2.storyGenerator.impl.EventImpl <em>Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.EventImpl
     * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl#getEvent()
     * @generated
     */
    EClass EVENT = eINSTANCE.getEvent();

    /**
     * The meta object literal for the '<em><b>Abstract</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__ABSTRACT = eINSTANCE.getEvent_Abstract();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__NAME = eINSTANCE.getEvent_Name();

    /**
     * The meta object literal for the '<em><b>Super Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVENT__SUPER_TYPE = eINSTANCE.getEvent_SuperType();

    /**
     * The meta object literal for the '<em><b>Conditions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVENT__CONDITIONS = eINSTANCE.getEvent_Conditions();

    /**
     * The meta object literal for the '{@link br.ufes.inf.mdd.trab2.storyGenerator.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.ConditionImpl
     * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '<em><b>Bool Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION__BOOL_EXP = eINSTANCE.getCondition_BoolExp();

    /**
     * The meta object literal for the '{@link br.ufes.inf.mdd.trab2.storyGenerator.impl.BoolExpImpl <em>Bool Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.BoolExpImpl
     * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl#getBoolExp()
     * @generated
     */
    EClass BOOL_EXP = eINSTANCE.getBoolExp();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOOL_EXP__LEFT = eINSTANCE.getBoolExp_Left();

    /**
     * The meta object literal for the '<em><b>Bool Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOL_EXP__BOOL_OP = eINSTANCE.getBoolExp_BoolOp();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOOL_EXP__RIGHT = eINSTANCE.getBoolExp_Right();

    /**
     * The meta object literal for the '<em><b>Par Bool Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOOL_EXP__PAR_BOOL_EXP = eINSTANCE.getBoolExp_ParBoolExp();

    /**
     * The meta object literal for the '<em><b>Binary Bool</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOOL_EXP__BINARY_BOOL = eINSTANCE.getBoolExp_BinaryBool();

    /**
     * The meta object literal for the '<em><b>Binary Qnty</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOOL_EXP__BINARY_QNTY = eINSTANCE.getBoolExp_BinaryQnty();

    /**
     * The meta object literal for the '<em><b>Negate Bool Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOOL_EXP__NEGATE_BOOL_EXP = eINSTANCE.getBoolExp_NegateBoolExp();

    /**
     * The meta object literal for the '<em><b>Unary Bool</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOOL_EXP__UNARY_BOOL = eINSTANCE.getBoolExp_UnaryBool();

    /**
     * The meta object literal for the '{@link br.ufes.inf.mdd.trab2.storyGenerator.impl.BinaryBoolExpImpl <em>Binary Bool Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.BinaryBoolExpImpl
     * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl#getBinaryBoolExp()
     * @generated
     */
    EClass BINARY_BOOL_EXP = eINSTANCE.getBinaryBoolExp();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BINARY_BOOL_EXP__LEFT = eINSTANCE.getBinaryBoolExp_Left();

    /**
     * The meta object literal for the '<em><b>Bool Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BINARY_BOOL_EXP__BOOL_OP = eINSTANCE.getBinaryBoolExp_BoolOp();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BINARY_BOOL_EXP__RIGHT = eINSTANCE.getBinaryBoolExp_Right();

    /**
     * The meta object literal for the '{@link br.ufes.inf.mdd.trab2.storyGenerator.impl.BinaryQntyExpImpl <em>Binary Qnty Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.BinaryQntyExpImpl
     * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl#getBinaryQntyExp()
     * @generated
     */
    EClass BINARY_QNTY_EXP = eINSTANCE.getBinaryQntyExp();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BINARY_QNTY_EXP__LEFT = eINSTANCE.getBinaryQntyExp_Left();

    /**
     * The meta object literal for the '<em><b>Num Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BINARY_QNTY_EXP__NUM_OP = eINSTANCE.getBinaryQntyExp_NumOp();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BINARY_QNTY_EXP__RIGHT = eINSTANCE.getBinaryQntyExp_Right();

    /**
     * The meta object literal for the '{@link br.ufes.inf.mdd.trab2.storyGenerator.impl.UnaryBoolExpImpl <em>Unary Bool Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.UnaryBoolExpImpl
     * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl#getUnaryBoolExp()
     * @generated
     */
    EClass UNARY_BOOL_EXP = eINSTANCE.getUnaryBoolExp();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNARY_BOOL_EXP__ID = eINSTANCE.getUnaryBoolExp_Id();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNARY_BOOL_EXP__VALUE = eINSTANCE.getUnaryBoolExp_Value();

    /**
     * The meta object literal for the '{@link br.ufes.inf.mdd.trab2.storyGenerator.impl.NegateBoolExpImpl <em>Negate Bool Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.NegateBoolExpImpl
     * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl#getNegateBoolExp()
     * @generated
     */
    EClass NEGATE_BOOL_EXP = eINSTANCE.getNegateBoolExp();

    /**
     * The meta object literal for the '<em><b>Bool Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NEGATE_BOOL_EXP__BOOL_EXP = eINSTANCE.getNegateBoolExp_BoolExp();

    /**
     * The meta object literal for the '{@link br.ufes.inf.mdd.trab2.storyGenerator.impl.UnaryQuantityExpImpl <em>Unary Quantity Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.UnaryQuantityExpImpl
     * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl#getUnaryQuantityExp()
     * @generated
     */
    EClass UNARY_QUANTITY_EXP = eINSTANCE.getUnaryQuantityExp();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNARY_QUANTITY_EXP__ID = eINSTANCE.getUnaryQuantityExp_Id();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNARY_QUANTITY_EXP__VALUE = eINSTANCE.getUnaryQuantityExp_Value();

    /**
     * The meta object literal for the '{@link br.ufes.inf.mdd.trab2.storyGenerator.AttrType <em>Attr Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.inf.mdd.trab2.storyGenerator.AttrType
     * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl#getAttrType()
     * @generated
     */
    EEnum ATTR_TYPE = eINSTANCE.getAttrType();

    /**
     * The meta object literal for the '{@link br.ufes.inf.mdd.trab2.storyGenerator.BooleanValue <em>Boolean Value</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.inf.mdd.trab2.storyGenerator.BooleanValue
     * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl#getBooleanValue()
     * @generated
     */
    EEnum BOOLEAN_VALUE = eINSTANCE.getBooleanValue();

    /**
     * The meta object literal for the '{@link br.ufes.inf.mdd.trab2.storyGenerator.NumOp <em>Num Op</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.inf.mdd.trab2.storyGenerator.NumOp
     * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl#getNumOp()
     * @generated
     */
    EEnum NUM_OP = eINSTANCE.getNumOp();

    /**
     * The meta object literal for the '{@link br.ufes.inf.mdd.trab2.storyGenerator.BoolOp <em>Bool Op</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.inf.mdd.trab2.storyGenerator.BoolOp
     * @see br.ufes.inf.mdd.trab2.storyGenerator.impl.StoryGeneratorPackageImpl#getBoolOp()
     * @generated
     */
    EEnum BOOL_OP = eINSTANCE.getBoolOp();

  }

} //StoryGeneratorPackage
