/*
 * generated by Xtext 2.17.0
 */
package br.ufes.inf.ui.tests;

import br.ufes.inf.pg.ui.internal.PgActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class StoryGenUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return PgActivator.getInstance().getInjector("br.ufes.inf.StoryGen");
	}

}
