/*
 * generated by Xtext 2.17.0
 */
package br.ufes.inf.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractStoryGenScopeProvider extends DelegatingScopeProvider {
}
