/**
 * generated by Xtext 2.17.0
 */
package br.ufes.inf.storyGen;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Story</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.inf.storyGen.Story#getWorld <em>World</em>}</li>
 *   <li>{@link br.ufes.inf.storyGen.Story#getEvents <em>Events</em>}</li>
 * </ul>
 *
 * @see br.ufes.inf.storyGen.StoryGenPackage#getStory()
 * @model
 * @generated
 */
public interface Story extends EObject
{
  /**
   * Returns the value of the '<em><b>World</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>World</em>' containment reference.
   * @see #setWorld(World)
   * @see br.ufes.inf.storyGen.StoryGenPackage#getStory_World()
   * @model containment="true"
   * @generated
   */
  World getWorld();

  /**
   * Sets the value of the '{@link br.ufes.inf.storyGen.Story#getWorld <em>World</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>World</em>' containment reference.
   * @see #getWorld()
   * @generated
   */
  void setWorld(World value);

  /**
   * Returns the value of the '<em><b>Events</b></em>' containment reference list.
   * The list contents are of type {@link br.ufes.inf.storyGen.Event}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Events</em>' containment reference list.
   * @see br.ufes.inf.storyGen.StoryGenPackage#getStory_Events()
   * @model containment="true"
   * @generated
   */
  EList<Event> getEvents();

} // Story
