/**
 * generated by Xtext 2.17.0
 */
package br.ufes.inf.storyGen;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>World</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.inf.storyGen.World#getAttributes <em>Attributes</em>}</li>
 * </ul>
 *
 * @see br.ufes.inf.storyGen.StoryGenPackage#getWorld()
 * @model
 * @generated
 */
public interface World extends EObject
{
  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link br.ufes.inf.storyGen.Attribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see br.ufes.inf.storyGen.StoryGenPackage#getWorld_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAttributes();

} // World
