/**
 * generated by Xtext 2.17.0
 */
package br.ufes.inf.pg.storyGen.impl;

import br.ufes.inf.pg.storyGen.Plot;
import br.ufes.inf.pg.storyGen.Space;
import br.ufes.inf.pg.storyGen.Story;
import br.ufes.inf.pg.storyGen.StoryData;
import br.ufes.inf.pg.storyGen.StoryGenPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Story</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.inf.pg.storyGen.impl.StoryImpl#getData <em>Data</em>}</li>
 *   <li>{@link br.ufes.inf.pg.storyGen.impl.StoryImpl#getSpace <em>Space</em>}</li>
 *   <li>{@link br.ufes.inf.pg.storyGen.impl.StoryImpl#getPlot <em>Plot</em>}</li>
 * </ul>
 *
 * @generated
 */
public class StoryImpl extends MinimalEObjectImpl.Container implements Story
{
  /**
   * The cached value of the '{@link #getData() <em>Data</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getData()
   * @generated
   * @ordered
   */
  protected StoryData data;

  /**
   * The cached value of the '{@link #getSpace() <em>Space</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpace()
   * @generated
   * @ordered
   */
  protected Space space;

  /**
   * The cached value of the '{@link #getPlot() <em>Plot</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPlot()
   * @generated
   * @ordered
   */
  protected Plot plot;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return StoryGenPackage.Literals.STORY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StoryData getData()
  {
    return data;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetData(StoryData newData, NotificationChain msgs)
  {
    StoryData oldData = data;
    data = newData;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, StoryGenPackage.STORY__DATA, oldData, newData);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setData(StoryData newData)
  {
    if (newData != data)
    {
      NotificationChain msgs = null;
      if (data != null)
        msgs = ((InternalEObject)data).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - StoryGenPackage.STORY__DATA, null, msgs);
      if (newData != null)
        msgs = ((InternalEObject)newData).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - StoryGenPackage.STORY__DATA, null, msgs);
      msgs = basicSetData(newData, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, StoryGenPackage.STORY__DATA, newData, newData));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Space getSpace()
  {
    return space;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSpace(Space newSpace, NotificationChain msgs)
  {
    Space oldSpace = space;
    space = newSpace;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, StoryGenPackage.STORY__SPACE, oldSpace, newSpace);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSpace(Space newSpace)
  {
    if (newSpace != space)
    {
      NotificationChain msgs = null;
      if (space != null)
        msgs = ((InternalEObject)space).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - StoryGenPackage.STORY__SPACE, null, msgs);
      if (newSpace != null)
        msgs = ((InternalEObject)newSpace).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - StoryGenPackage.STORY__SPACE, null, msgs);
      msgs = basicSetSpace(newSpace, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, StoryGenPackage.STORY__SPACE, newSpace, newSpace));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Plot getPlot()
  {
    return plot;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPlot(Plot newPlot, NotificationChain msgs)
  {
    Plot oldPlot = plot;
    plot = newPlot;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, StoryGenPackage.STORY__PLOT, oldPlot, newPlot);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPlot(Plot newPlot)
  {
    if (newPlot != plot)
    {
      NotificationChain msgs = null;
      if (plot != null)
        msgs = ((InternalEObject)plot).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - StoryGenPackage.STORY__PLOT, null, msgs);
      if (newPlot != null)
        msgs = ((InternalEObject)newPlot).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - StoryGenPackage.STORY__PLOT, null, msgs);
      msgs = basicSetPlot(newPlot, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, StoryGenPackage.STORY__PLOT, newPlot, newPlot));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case StoryGenPackage.STORY__DATA:
        return basicSetData(null, msgs);
      case StoryGenPackage.STORY__SPACE:
        return basicSetSpace(null, msgs);
      case StoryGenPackage.STORY__PLOT:
        return basicSetPlot(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case StoryGenPackage.STORY__DATA:
        return getData();
      case StoryGenPackage.STORY__SPACE:
        return getSpace();
      case StoryGenPackage.STORY__PLOT:
        return getPlot();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case StoryGenPackage.STORY__DATA:
        setData((StoryData)newValue);
        return;
      case StoryGenPackage.STORY__SPACE:
        setSpace((Space)newValue);
        return;
      case StoryGenPackage.STORY__PLOT:
        setPlot((Plot)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case StoryGenPackage.STORY__DATA:
        setData((StoryData)null);
        return;
      case StoryGenPackage.STORY__SPACE:
        setSpace((Space)null);
        return;
      case StoryGenPackage.STORY__PLOT:
        setPlot((Plot)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case StoryGenPackage.STORY__DATA:
        return data != null;
      case StoryGenPackage.STORY__SPACE:
        return space != null;
      case StoryGenPackage.STORY__PLOT:
        return plot != null;
    }
    return super.eIsSet(featureID);
  }

} //StoryImpl
