/*
 * generated by Xtext 2.17.0
 */
package br.ufes.inf.mdd.trab2.ide


/**
 * Use this class to register ide components.
 */
class StoryGeneratorIdeModule extends AbstractStoryGeneratorIdeModule {
}
