/*
 * generated by Xtext 2.14.0
 */
package br.ufes.inf.mdd.trab2.ui.tests;

import br.ufes.inf.mdd.trab2.ui.internal.Trab2Activator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class StoryGeneratorUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Trab2Activator.getInstance().getInjector("br.ufes.inf.mdd.trab2.StoryGenerator");
	}

}
