/**
 * generated by Xtext 2.17.0
 */
package br.ufes.inf.validation;

import br.ufes.inf.validation.AbstractStoryGenValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class StoryGenValidator extends AbstractStoryGenValidator {
}
