/**
 * generated by Xtext 2.17.0
 */
package br.ufes.inf.pg.storyGen;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Action Type</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see br.ufes.inf.pg.storyGen.StoryGenPackage#getActionType()
 * @model
 * @generated
 */
public enum ActionType implements Enumerator
{
  /**
   * The '<em><b>VISUAL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #VISUAL_VALUE
   * @generated
   * @ordered
   */
  VISUAL(0, "VISUAL", "visual"),

  /**
   * The '<em><b>INTERACTION</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INTERACTION_VALUE
   * @generated
   * @ordered
   */
  INTERACTION(1, "INTERACTION", "interaction"),

  /**
   * The '<em><b>MOVEMENT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MOVEMENT_VALUE
   * @generated
   * @ordered
   */
  MOVEMENT(2, "MOVEMENT", "movement"),

  /**
   * The '<em><b>COMMUNICATION</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #COMMUNICATION_VALUE
   * @generated
   * @ordered
   */
  COMMUNICATION(3, "COMMUNICATION", "communication"),

  /**
   * The '<em><b>COMBAT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #COMBAT_VALUE
   * @generated
   * @ordered
   */
  COMBAT(4, "COMBAT", "combat"),

  /**
   * The '<em><b>IDLE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #IDLE_VALUE
   * @generated
   * @ordered
   */
  IDLE(5, "IDLE", "idle");

  /**
   * The '<em><b>VISUAL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #VISUAL
   * @model literal="visual"
   * @generated
   * @ordered
   */
  public static final int VISUAL_VALUE = 0;

  /**
   * The '<em><b>INTERACTION</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INTERACTION
   * @model literal="interaction"
   * @generated
   * @ordered
   */
  public static final int INTERACTION_VALUE = 1;

  /**
   * The '<em><b>MOVEMENT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MOVEMENT
   * @model literal="movement"
   * @generated
   * @ordered
   */
  public static final int MOVEMENT_VALUE = 2;

  /**
   * The '<em><b>COMMUNICATION</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #COMMUNICATION
   * @model literal="communication"
   * @generated
   * @ordered
   */
  public static final int COMMUNICATION_VALUE = 3;

  /**
   * The '<em><b>COMBAT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #COMBAT
   * @model literal="combat"
   * @generated
   * @ordered
   */
  public static final int COMBAT_VALUE = 4;

  /**
   * The '<em><b>IDLE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #IDLE
   * @model literal="idle"
   * @generated
   * @ordered
   */
  public static final int IDLE_VALUE = 5;

  /**
   * An array of all the '<em><b>Action Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final ActionType[] VALUES_ARRAY =
    new ActionType[]
    {
      VISUAL,
      INTERACTION,
      MOVEMENT,
      COMMUNICATION,
      COMBAT,
      IDLE,
    };

  /**
   * A public read-only list of all the '<em><b>Action Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<ActionType> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Action Type</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ActionType get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ActionType result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Action Type</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ActionType getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ActionType result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Action Type</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ActionType get(int value)
  {
    switch (value)
    {
      case VISUAL_VALUE: return VISUAL;
      case INTERACTION_VALUE: return INTERACTION;
      case MOVEMENT_VALUE: return MOVEMENT;
      case COMMUNICATION_VALUE: return COMMUNICATION;
      case COMBAT_VALUE: return COMBAT;
      case IDLE_VALUE: return IDLE;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private ActionType(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //ActionType
