/**
 * generated by Xtext 2.17.0
 */
package br.ufes.inf.pg.storyGen;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.inf.pg.storyGen.ActionEvent#getType <em>Type</em>}</li>
 *   <li>{@link br.ufes.inf.pg.storyGen.ActionEvent#getActor <em>Actor</em>}</li>
 * </ul>
 *
 * @see br.ufes.inf.pg.storyGen.StoryGenPackage#getActionEvent()
 * @model
 * @generated
 */
public interface ActionEvent extends Event
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link br.ufes.inf.pg.storyGen.ActionType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see br.ufes.inf.pg.storyGen.ActionType
   * @see #setType(ActionType)
   * @see br.ufes.inf.pg.storyGen.StoryGenPackage#getActionEvent_Type()
   * @model
   * @generated
   */
  ActionType getType();

  /**
   * Sets the value of the '{@link br.ufes.inf.pg.storyGen.ActionEvent#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see br.ufes.inf.pg.storyGen.ActionType
   * @see #getType()
   * @generated
   */
  void setType(ActionType value);

  /**
   * Returns the value of the '<em><b>Actor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actor</em>' reference.
   * @see #setActor(Actor)
   * @see br.ufes.inf.pg.storyGen.StoryGenPackage#getActionEvent_Actor()
   * @model
   * @generated
   */
  Actor getActor();

  /**
   * Sets the value of the '{@link br.ufes.inf.pg.storyGen.ActionEvent#getActor <em>Actor</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Actor</em>' reference.
   * @see #getActor()
   * @generated
   */
  void setActor(Actor value);

} // ActionEvent
