/**
 * generated by Xtext 2.17.0
 */
package br.ufes.inf.pg.storyGen;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Attribute Setting Frequency</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see br.ufes.inf.pg.storyGen.StoryGenPackage#getAttributeSettingFrequency()
 * @model
 * @generated
 */
public enum AttributeSettingFrequency implements Enumerator
{
  /**
   * The '<em><b>EVERY EVENT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EVERY_EVENT_VALUE
   * @generated
   * @ordered
   */
  EVERY_EVENT(0, "EVERY_EVENT", "every event"),

  /**
   * The '<em><b>EVERY HAPPENING</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EVERY_HAPPENING_VALUE
   * @generated
   * @ordered
   */
  EVERY_HAPPENING(1, "EVERY_HAPPENING", "every happening"),

  /**
   * The '<em><b>EVERY ACTION</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EVERY_ACTION_VALUE
   * @generated
   * @ordered
   */
  EVERY_ACTION(2, "EVERY_ACTION", "every action"),

  /**
   * The '<em><b>EVERY PLAYER ACTION</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EVERY_PLAYER_ACTION_VALUE
   * @generated
   * @ordered
   */
  EVERY_PLAYER_ACTION(3, "EVERY_PLAYER_ACTION", "every player action");

  /**
   * The '<em><b>EVERY EVENT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EVERY_EVENT
   * @model literal="every event"
   * @generated
   * @ordered
   */
  public static final int EVERY_EVENT_VALUE = 0;

  /**
   * The '<em><b>EVERY HAPPENING</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EVERY_HAPPENING
   * @model literal="every happening"
   * @generated
   * @ordered
   */
  public static final int EVERY_HAPPENING_VALUE = 1;

  /**
   * The '<em><b>EVERY ACTION</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EVERY_ACTION
   * @model literal="every action"
   * @generated
   * @ordered
   */
  public static final int EVERY_ACTION_VALUE = 2;

  /**
   * The '<em><b>EVERY PLAYER ACTION</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EVERY_PLAYER_ACTION
   * @model literal="every player action"
   * @generated
   * @ordered
   */
  public static final int EVERY_PLAYER_ACTION_VALUE = 3;

  /**
   * An array of all the '<em><b>Attribute Setting Frequency</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final AttributeSettingFrequency[] VALUES_ARRAY =
    new AttributeSettingFrequency[]
    {
      EVERY_EVENT,
      EVERY_HAPPENING,
      EVERY_ACTION,
      EVERY_PLAYER_ACTION,
    };

  /**
   * A public read-only list of all the '<em><b>Attribute Setting Frequency</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<AttributeSettingFrequency> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Attribute Setting Frequency</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static AttributeSettingFrequency get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      AttributeSettingFrequency result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Attribute Setting Frequency</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static AttributeSettingFrequency getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      AttributeSettingFrequency result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Attribute Setting Frequency</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static AttributeSettingFrequency get(int value)
  {
    switch (value)
    {
      case EVERY_EVENT_VALUE: return EVERY_EVENT;
      case EVERY_HAPPENING_VALUE: return EVERY_HAPPENING;
      case EVERY_ACTION_VALUE: return EVERY_ACTION;
      case EVERY_PLAYER_ACTION_VALUE: return EVERY_PLAYER_ACTION;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private AttributeSettingFrequency(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //AttributeSettingFrequency
