/**
 * generated by Xtext 2.17.0
 */
package br.ufes.inf.pg.storyGen;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute Setting</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.inf.pg.storyGen.AttributeSetting#isPositive <em>Positive</em>}</li>
 *   <li>{@link br.ufes.inf.pg.storyGen.AttributeSetting#isNegative <em>Negative</em>}</li>
 *   <li>{@link br.ufes.inf.pg.storyGen.AttributeSetting#getAmount <em>Amount</em>}</li>
 *   <li>{@link br.ufes.inf.pg.storyGen.AttributeSetting#getFrequency <em>Frequency</em>}</li>
 * </ul>
 *
 * @see br.ufes.inf.pg.storyGen.StoryGenPackage#getAttributeSetting()
 * @model
 * @generated
 */
public interface AttributeSetting extends EObject
{
  /**
   * Returns the value of the '<em><b>Positive</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Positive</em>' attribute.
   * @see #setPositive(boolean)
   * @see br.ufes.inf.pg.storyGen.StoryGenPackage#getAttributeSetting_Positive()
   * @model
   * @generated
   */
  boolean isPositive();

  /**
   * Sets the value of the '{@link br.ufes.inf.pg.storyGen.AttributeSetting#isPositive <em>Positive</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Positive</em>' attribute.
   * @see #isPositive()
   * @generated
   */
  void setPositive(boolean value);

  /**
   * Returns the value of the '<em><b>Negative</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Negative</em>' attribute.
   * @see #setNegative(boolean)
   * @see br.ufes.inf.pg.storyGen.StoryGenPackage#getAttributeSetting_Negative()
   * @model
   * @generated
   */
  boolean isNegative();

  /**
   * Sets the value of the '{@link br.ufes.inf.pg.storyGen.AttributeSetting#isNegative <em>Negative</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Negative</em>' attribute.
   * @see #isNegative()
   * @generated
   */
  void setNegative(boolean value);

  /**
   * Returns the value of the '<em><b>Amount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Amount</em>' attribute.
   * @see #setAmount(int)
   * @see br.ufes.inf.pg.storyGen.StoryGenPackage#getAttributeSetting_Amount()
   * @model
   * @generated
   */
  int getAmount();

  /**
   * Sets the value of the '{@link br.ufes.inf.pg.storyGen.AttributeSetting#getAmount <em>Amount</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Amount</em>' attribute.
   * @see #getAmount()
   * @generated
   */
  void setAmount(int value);

  /**
   * Returns the value of the '<em><b>Frequency</b></em>' attribute.
   * The literals are from the enumeration {@link br.ufes.inf.pg.storyGen.AttributeSettingFrequency}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Frequency</em>' attribute.
   * @see br.ufes.inf.pg.storyGen.AttributeSettingFrequency
   * @see #setFrequency(AttributeSettingFrequency)
   * @see br.ufes.inf.pg.storyGen.StoryGenPackage#getAttributeSetting_Frequency()
   * @model
   * @generated
   */
  AttributeSettingFrequency getFrequency();

  /**
   * Sets the value of the '{@link br.ufes.inf.pg.storyGen.AttributeSetting#getFrequency <em>Frequency</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Frequency</em>' attribute.
   * @see br.ufes.inf.pg.storyGen.AttributeSettingFrequency
   * @see #getFrequency()
   * @generated
   */
  void setFrequency(AttributeSettingFrequency value);

} // AttributeSetting
