/**
 * generated by Xtext 2.17.0
 */
package br.ufes.inf.pg.storyGen;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Change</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.inf.pg.storyGen.Change#getAttribute <em>Attribute</em>}</li>
 *   <li>{@link br.ufes.inf.pg.storyGen.Change#getOp <em>Op</em>}</li>
 *   <li>{@link br.ufes.inf.pg.storyGen.Change#getTerm <em>Term</em>}</li>
 * </ul>
 *
 * @see br.ufes.inf.pg.storyGen.StoryGenPackage#getChange()
 * @model
 * @generated
 */
public interface Change extends EObject
{
  /**
   * Returns the value of the '<em><b>Attribute</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute</em>' reference.
   * @see #setAttribute(Attribute)
   * @see br.ufes.inf.pg.storyGen.StoryGenPackage#getChange_Attribute()
   * @model
   * @generated
   */
  Attribute getAttribute();

  /**
   * Sets the value of the '{@link br.ufes.inf.pg.storyGen.Change#getAttribute <em>Attribute</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute</em>' reference.
   * @see #getAttribute()
   * @generated
   */
  void setAttribute(Attribute value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * The literals are from the enumeration {@link br.ufes.inf.pg.storyGen.AttributionOperator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see br.ufes.inf.pg.storyGen.AttributionOperator
   * @see #setOp(AttributionOperator)
   * @see br.ufes.inf.pg.storyGen.StoryGenPackage#getChange_Op()
   * @model
   * @generated
   */
  AttributionOperator getOp();

  /**
   * Sets the value of the '{@link br.ufes.inf.pg.storyGen.Change#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see br.ufes.inf.pg.storyGen.AttributionOperator
   * @see #getOp()
   * @generated
   */
  void setOp(AttributionOperator value);

  /**
   * Returns the value of the '<em><b>Term</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Term</em>' containment reference.
   * @see #setTerm(Term)
   * @see br.ufes.inf.pg.storyGen.StoryGenPackage#getChange_Term()
   * @model containment="true"
   * @generated
   */
  Term getTerm();

  /**
   * Sets the value of the '{@link br.ufes.inf.pg.storyGen.Change#getTerm <em>Term</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Term</em>' containment reference.
   * @see #getTerm()
   * @generated
   */
  void setTerm(Term value);

} // Change
