/**
 * generated by Xtext 2.17.0
 */
package br.ufes.inf.pg.storyGen;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see br.ufes.inf.pg.storyGen.StoryGenPackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends EObject
{
} // Condition
