/**
 * generated by Xtext 2.17.0
 */
package br.ufes.inf.pg.storyGen;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Existent Change</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.inf.pg.storyGen.ExistentChange#getExistent <em>Existent</em>}</li>
 * </ul>
 *
 * @see br.ufes.inf.pg.storyGen.StoryGenPackage#getExistentChange()
 * @model
 * @generated
 */
public interface ExistentChange extends Change
{
  /**
   * Returns the value of the '<em><b>Existent</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Existent</em>' reference.
   * @see #setExistent(Existent)
   * @see br.ufes.inf.pg.storyGen.StoryGenPackage#getExistentChange_Existent()
   * @model
   * @generated
   */
  Existent getExistent();

  /**
   * Sets the value of the '{@link br.ufes.inf.pg.storyGen.ExistentChange#getExistent <em>Existent</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Existent</em>' reference.
   * @see #getExistent()
   * @generated
   */
  void setExistent(Existent value);

} // ExistentChange
