/**
 * generated by Xtext 2.17.0
 */
package br.ufes.inf.pg.storyGen;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Order Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.inf.pg.storyGen.OrderCondition#getOrder <em>Order</em>}</li>
 *   <li>{@link br.ufes.inf.pg.storyGen.OrderCondition#getEvent <em>Event</em>}</li>
 * </ul>
 *
 * @see br.ufes.inf.pg.storyGen.StoryGenPackage#getOrderCondition()
 * @model
 * @generated
 */
public interface OrderCondition extends Condition
{
  /**
   * Returns the value of the '<em><b>Order</b></em>' attribute.
   * The literals are from the enumeration {@link br.ufes.inf.pg.storyGen.Order}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Order</em>' attribute.
   * @see br.ufes.inf.pg.storyGen.Order
   * @see #setOrder(Order)
   * @see br.ufes.inf.pg.storyGen.StoryGenPackage#getOrderCondition_Order()
   * @model
   * @generated
   */
  Order getOrder();

  /**
   * Sets the value of the '{@link br.ufes.inf.pg.storyGen.OrderCondition#getOrder <em>Order</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Order</em>' attribute.
   * @see br.ufes.inf.pg.storyGen.Order
   * @see #getOrder()
   * @generated
   */
  void setOrder(Order value);

  /**
   * Returns the value of the '<em><b>Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event</em>' reference.
   * @see #setEvent(Event)
   * @see br.ufes.inf.pg.storyGen.StoryGenPackage#getOrderCondition_Event()
   * @model
   * @generated
   */
  Event getEvent();

  /**
   * Sets the value of the '{@link br.ufes.inf.pg.storyGen.OrderCondition#getEvent <em>Event</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event</em>' reference.
   * @see #getEvent()
   * @generated
   */
  void setEvent(Event value);

} // OrderCondition
