/**
 * generated by Xtext 2.17.0
 */
package br.ufes.inf.pg.storyGen;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Story Data Change</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see br.ufes.inf.pg.storyGen.StoryGenPackage#getStoryDataChange()
 * @model
 * @generated
 */
public interface StoryDataChange extends Change
{
} // StoryDataChange
