/**
 * generated by Xtext 2.17.0
 */
package br.ufes.inf.pg.storyGen;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Term</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see br.ufes.inf.pg.storyGen.StoryGenPackage#getTerm()
 * @model
 * @generated
 */
public interface Term extends Expression
{
} // Term
