/**
 * generated by Xtext 2.17.0
 */
package br.ufes.inf.generator;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class StoryGenGenerator /* implements AbstractGenerator  */{
  @Override
  public void doGenerate(final /* Resource */Object resource, final /* IFileSystemAccess2 */Object fsa, final /* IGeneratorContext */Object context) {
  }
}
