/*
 * generated by Xtext 2.14.0
 */
package br.ufes.inf.mdd.trab2.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class StoryGeneratorAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("br/ufes/inf/mdd/trab2/parser/antlr/internal/InternalStoryGenerator.tokens");
	}
}
