/*
 * generated by Xtext 2.14.0
 */
package br.ufes.inf.mdd.trab2.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractStoryGeneratorValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(br.ufes.inf.mdd.trab2.storyGenerator.StoryGeneratorPackage.eINSTANCE);
		return result;
	}
}
