/**
 * generated by Xtext 2.17.0
 */
package br.ufes.inf.pg.ui.contentassist;

import br.ufes.inf.pg.ui.contentassist.AbstractStoryGenProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class StoryGenProposalProvider extends AbstractStoryGenProposalProvider {
}
