/**
 * generated by Xtext 2.17.0
 */
package br.ufes.inf.mdd.trab2.ide;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class StoryGeneratorIdeSetup /* implements StoryGeneratorStandaloneSetup  */{
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nStoryGeneratorRuntimeModule cannot be resolved."
      + "\nType mismatch: cannot convert from StoryGeneratorIdeModule to Module");
  }
}
