/*
 * generated by Xtext 2.17.0
 */
package br.ufes.inf.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractStoryGenValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(br.ufes.inf.storyGen.StoryGenPackage.eINSTANCE);
		return result;
	}
}
